# Generated by Django 6.0 on 2025-12-20 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('NSRNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=1)),
                ('Establishment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('HospitalName', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPractice',
            fields=[
                ('pk', models.CompositePrimaryKey('NSRNo', 'Field', blank=True, editable=False, primary_key=True, serialize=False)),
                ('NSRNo', models.CharField(max_length=10)),
                ('Field', models.CharField(max_length=500)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wthehealth.doctor')),
            ],
        ),
    ]
