# Generated by Django 6.0 on 2025-12-21 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wthehealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='FieldOfPractice',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.CreateModel(
            name='HospitalDoctor',
            fields=[
                ('pk', models.CompositePrimaryKey('HospitalName', 'NSRNo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('HospitalName', models.CharField(max_length=200)),
                ('NSRNo', models.CharField(max_length=10)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wthehealth.doctor')),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wthehealth.hospital')),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorPractice',
        ),
    ]
