# Generated by Django 6.0 on 2025-12-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wthehealth', '0002_doctor_fieldofpractice_hospitaldoctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalDoctor',
        ),
    ]
