# Generated by Django 6.0 on 2025-12-21 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wthehealth', '0003_delete_hospitaldoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciaty',
            fields=[
                ('SpeciatyID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('SurgeryID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
                ('Speciaty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wthehealth.speciaty')),
            ],
        ),
    ]
