# Generated by Django 6.0 on 2026-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wthehealth', '0004_speciaty_surgery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitaldoctor',
            fields=[
                ('pk', models.CompositePrimaryKey('hospitalname', 'nsrno', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'HospitalDoctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospitalspecialty',
            fields=[
                ('pk', models.CompositePrimaryKey('hospitalname', 'specialtyid', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'HospitalSpecialty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospprocedure',
            fields=[
                ('procedureid', models.CharField(db_collation='utf8mb3_general_ci', db_column='ProcedureID', max_length=150, primary_key=True, serialize=False)),
                ('description', models.CharField(db_collation='utf8mb3_general_ci', db_column='Description', max_length=500)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=14)),
                ('patienttype', models.TextField(blank=True, db_column='PatientType', null=True)),
            ],
            options={
                'db_table': 'HospProcedure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('reviewtext', models.CharField(blank=True, db_column='ReviewText', max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('reviewdatetime', models.DateField(blank=True, db_column='ReviewDatetime', null=True)),
                ('author', models.CharField(blank=True, db_column='Author', max_length=255, null=True)),
                ('hospname', models.CharField(blank=True, db_column='HospName', max_length=255, null=True)),
                ('doctor', models.CharField(blank=True, db_column='Doctor', max_length=255, null=True)),
                ('specialty', models.CharField(blank=True, db_column='Specialty', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('specialtyid', models.CharField(db_collation='utf8mb3_general_ci', db_column='SpecialtyID', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(db_collation='utf8mb3_general_ci', db_column='Description', max_length=200)),
            ],
            options={
                'db_table': 'Specialty',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='Speciaty',
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Speciaty',
        ),
        migrations.DeleteModel(
            name='Surgery',
        ),
    ]
